--CREATE TABELE--
create table public."Colaborador" (
  id bigint generated by default as identity not null,
  "Nome" character varying not null,
  "Salario" numeric null,
  "DeptID" bigint not null,
  constraint Colaborador_pkey primary key (id, "DeptID"),
  constraint Colaborador_DeptID_fkey foreign KEY ("DeptID") references "Departamento" (id)
) TABLESPACE pg_default;

--INSERT INTO--
INSERT INTO "public"."Colaborador" ("id", "Nome", "Salario", "DeptID") 
		VALUES 
	('1', 'Joe', '70000', '1'), 
	('2', 'Henry', '80000', '2'), 
	('3', 'Sam', '60000', '2'), 
	('4', 'Max', '90000', '1');