--CREATE TABLE--
create table public."Departamento" (
  id bigint generated by default as identity not null,
  "Nome" character varying not null,
  constraint Departamento_id_key unique (id)
) TABLESPACE pg_default;

--INSERT INTO--
INSERT INTO "public"."Departamento" ("id", "Nome") 
		VALUES 
	('1', 'TI'), ('2', 'Vendas');